version = 0.1
[default.deploy.parameters]
stack_name = "load-shedding-cal"
resolve_s3 = true
s3_prefix = "load-shedding-cal"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Timeout=\"10\" MemorySize=\"128\" Entrypoint=\"io.github.daveduthie.load-shedding-cal-lambda.core\""
image_repositories = []
profile = "dev"
